// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Anime struct {
	ID          string `json:"id" bson:"_id"`
	Title       string `json:"title"`
	Image       string `json:"image"`
	Description string `json:"description"`
	Genre       *Genre `json:"genre"`
}

type Genre struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Manga struct {
	ID          string `json:"id" bson:"_id"`
	Title       string `json:"title"`
	Image       string `json:"image"`
	Description string `json:"description"`
	Genre       *Genre `json:"genre"`
}

type NewAnime struct {
	Title       string `json:"title"`
	Image       string `json:"image"`
	Description string `json:"description"`
	GenreID     string `json:"genreId"`
}

type NewManga struct {
	Title       string `json:"title"`
	Image       string `json:"image"`
	Description string `json:"description"`
	GenreID     string `json:"genreId"`
}
